#!/usr/bin/env bash
set -euo pipefail

# Create a compact submission package after final benchmark/report generation.

PACKAGE_NAME="${PACKAGE_NAME:-HPC_Matrix_MPI_Submission}"
OUT_DIR="${OUT_DIR:-submission/${PACKAGE_NAME}}"
ZIP_PATH="${ZIP_PATH:-submission/${PACKAGE_NAME}.zip}"
SKIP_PREFLIGHT="${SKIP_PREFLIGHT:-0}"

echo "Packaging submission into: $OUT_DIR"

if [[ "$SKIP_PREFLIGHT" != "1" ]]; then
  bash scripts/preflight_submission.sh
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [[ -e "$src" ]]; then
    mkdir -p "$(dirname "$OUT_DIR/$dst")"
    cp -a "$src" "$OUT_DIR/$dst"
  else
    echo "WARN missing: $src"
  fi
}

# Core project files
copy_if_exists README.md README.md
copy_if_exists START_HERE.md START_HERE.md
copy_if_exists Makefile Makefile
copy_if_exists src/matrix_hpc.c src/matrix_hpc.c

# Minimal config
copy_if_exists config/hosts.example config/hosts.example
copy_if_exists config/group_info.example.txt config/group_info.example.txt
copy_if_exists config/group_info.txt config/group_info.txt

# Scripts needed to build, benchmark, generate report, and package evidence
for f in \
  capture_environment.sh check_cluster.sh check_local_env.sh compare_checksums.py \
  create_report_docx.py demo.sh make_chart_svgs.py package_submission.sh \
  preflight_submission.sh prepare_group_info.sh run_benchmark.sh \
  run_local_pipeline.sh run_multinode.sh run_multinode_pipeline.sh \
  setup_ubuntu.sh summarize_results.py sync_to_nodes.sh \
  windows_package_submission.ps1 windows_prepare_group_info.ps1 \
  windows_run_demo.ps1 windows_run_local_pipeline.ps1 windows_setup_wsl.ps1
do
  copy_if_exists "scripts/$f" "scripts/$f"
done

# Minimal docs
copy_if_exists docs/CODE_WALKTHROUGH.md docs/CODE_WALKTHROUGH.md
copy_if_exists docs/DEMO_CHEAT_SHEET.md docs/DEMO_CHEAT_SHEET.md
copy_if_exists docs/INSTALL_FOR_TEAMMATES.md docs/INSTALL_FOR_TEAMMATES.md
copy_if_exists docs/THREE_PHYSICAL_MACHINES_SETUP.md docs/THREE_PHYSICAL_MACHINES_SETUP.md
copy_if_exists docs/SUBMISSION_CHECKLIST.md docs/SUBMISSION_CHECKLIST.md
copy_if_exists docs/BaoCao_DeTai1_NhanMaTran_MPI.docx docs/BaoCao_DeTai1_NhanMaTran_MPI.docx
copy_if_exists docs/charts docs/charts

# Evidence generated by benchmark
copy_if_exists results results
copy_if_exists outputs outputs

find "$OUT_DIR" -type d -name "__pycache__" -prune -exec rm -rf {} +
find "$OUT_DIR" -type f \( -name "*.tmp" -o -name "*.log" -o -name "*.bak" \) -delete

mkdir -p "$(dirname "$ZIP_PATH")"
if command -v zip >/dev/null 2>&1; then
  rm -f "$ZIP_PATH"
  (cd "$(dirname "$OUT_DIR")" && zip -qr "$(basename "$ZIP_PATH")" "$(basename "$OUT_DIR")")
  echo "Zip package written to: $ZIP_PATH"
else
  echo "zip command not found; folder package is ready at: $OUT_DIR"
fi

echo "Submission package ready."
